# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tmp/tmp.hlf3HLCa6y/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_auto_us_1/project_1_auto_us_1.xci
# IP: The module: 'project_1_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/tmp.hlf3HLCa6y/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_auto_us_1/project_1_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_auto_us_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /tmp/tmp.hlf3HLCa6y/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_auto_us_1/project_1_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /tmp/tmp.hlf3HLCa6y/temp/hwflow/hwflow_project_1/project_1.srcs/sources_1/bd/project_1/ip/project_1_auto_us_1/project_1_auto_us_1.xci
# IP: The module: 'project_1_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/tmp.hlf3HLCa6y/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_auto_us_1/project_1_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /tmp/tmp.hlf3HLCa6y/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/ip/project_1_auto_us_1/project_1_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_1_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
