# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/default.xdc

# Block Designs: bd/project_1/project_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1 || ORIG_REF_NAME==project_1} -quiet] -quiet

# IP: bd/project_1/ip/project_1_zynq_ultra_ps_e_0_0/project_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==project_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_axi_intc_0_0/project_1_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_axi_intc_0_0 || ORIG_REF_NAME==project_1_axi_intc_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_auto_us_0/project_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_auto_us_0 || ORIG_REF_NAME==project_1_auto_us_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_axi_interconnect_lpd_0/project_1_axi_interconnect_lpd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_axi_interconnect_lpd_0 || ORIG_REF_NAME==project_1_axi_interconnect_lpd_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_axi_register_slice_0_0/project_1_axi_register_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_axi_register_slice_0_0 || ORIG_REF_NAME==project_1_axi_register_slice_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_axi_vip_0_0/project_1_axi_vip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_axi_vip_0_0 || ORIG_REF_NAME==project_1_axi_vip_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_axi_vip_1_0/project_1_axi_vip_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_axi_vip_1_0 || ORIG_REF_NAME==project_1_axi_vip_1_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_clk_wiz_0_0/project_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_clk_wiz_0_0 || ORIG_REF_NAME==project_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_auto_us_1/project_1_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_auto_us_1 || ORIG_REF_NAME==project_1_auto_us_1} -quiet] -quiet

# IP: bd/project_1/ip/project_1_interconnect_axifull_0/project_1_interconnect_axifull_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_interconnect_axifull_0 || ORIG_REF_NAME==project_1_interconnect_axifull_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_interconnect_axihpm0fpd_0/project_1_interconnect_axihpm0fpd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_interconnect_axihpm0fpd_0 || ORIG_REF_NAME==project_1_interconnect_axihpm0fpd_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_auto_pc_0/project_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_auto_pc_0 || ORIG_REF_NAME==project_1_auto_pc_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_interconnect_axilite_0/project_1_interconnect_axilite_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_interconnect_axilite_0 || ORIG_REF_NAME==project_1_interconnect_axilite_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_proc_sys_reset_0_0/project_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_proc_sys_reset_0_0 || ORIG_REF_NAME==project_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_proc_sys_reset_1_0/project_1_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_proc_sys_reset_1_0 || ORIG_REF_NAME==project_1_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_proc_sys_reset_2_0/project_1_proc_sys_reset_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_proc_sys_reset_2_0 || ORIG_REF_NAME==project_1_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_proc_sys_reset_3_0/project_1_proc_sys_reset_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_proc_sys_reset_3_0 || ORIG_REF_NAME==project_1_proc_sys_reset_3_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_proc_sys_reset_4_0/project_1_proc_sys_reset_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_proc_sys_reset_4_0 || ORIG_REF_NAME==project_1_proc_sys_reset_4_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_proc_sys_reset_5_0/project_1_proc_sys_reset_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_proc_sys_reset_5_0 || ORIG_REF_NAME==project_1_proc_sys_reset_5_0} -quiet] -quiet

# IP: bd/project_1/ip/project_1_proc_sys_reset_6_0/project_1_proc_sys_reset_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==project_1_proc_sys_reset_6_0 || ORIG_REF_NAME==project_1_proc_sys_reset_6_0} -quiet] -quiet

# XDC: /tmp/tmp.hlf3HLCa6y/temp/hwflow/hwflow_project_1/project_1.gen/sources_1/bd/project_1/project_1_ooc.xdc
